### ISSUE TITLE
`quartz()` in macOS fails with `xpos`

### ISSUE THREAD

**Issue by matiasandina** [mjin1812/SMART#1]
This is a problem for people using SMART on macOS. It could be solved by checking how to configure successfully the `X11` environment in macOS (no longer ships with default config). But it would be much much better to solve it within the `.onAttach()` call. I asked a way to do this [here](https://stackoverflow.com/questions/58000221/plot-window-with-quartz-specify-xpos-or-bypass-xpos). Maybe we get some help.
For now, I'm by-passing the many many `quartz(xpos=xpos)` calls with a if/else statement. This is less than ideal...

**Comment by mjin1812** [comment]
Hi Matias,

Can you check whether this is fixed in the most recent .onAttach updates?

**Comment by matiasandina** [comment]
In principle, that should work. Looks like a better behavior than what I have now :). When we merge, I can also get rid of all the by-passes.
